### ISSUE TITLE
Sync API beta 

### ISSUE THREAD

**Issue by Bobspadger** [paypal/PayPal-Python-SDK#237]
* SDK/Library version: sync beta
* Environment: Sandbox
* Language, language version, and OS: Python 3.4.3 OSX 10.13

### Issue description

Following example to request info from Sync API

```python
import paypalrestsdk
env = paypalrestsdk.SandboxEnvironment(client_id=myclientid,
                                        client_secret=myclientsecret)

client = paypalrestsdk.PayPalHttpClient(environment=env)

one_week_ago = datetime.datetime.now() - datetime.timedelta(days=7)

one_week_ago_iso = one_week_ago.isoformat()

payment_sync = paypalrestsdk.SearchGetRequest()
payment_sync.body({
    "start_date" : "2018-01-22T18:01:46.627248"
})

```

Running debugger in Pycharm at the point I attempt to add to the .body() the search parameters I get

``` python   
"start_date" : "2018-01-22T18:01:46.627248"
TypeError: 'NoneType' object is not callable
```

Its dying in the `BufferedIncrementalDecoder` in `codecs.py`

Am I using the SearchGetRequest() incorrectly (I followed the pattern in the overview docs for the beta SDK which has 

```python
payment_create_request = paypalrestsdk.PaymentCreateRequest()
payment_create_request.body({
    "payer": {
        "payment_method": "paypal"
    },
    "intent": "sale",
    "transactions": [{
        "amount": {
            "total": "10",
            "currency": "USD"
        }
    }],
    "redirect_urls": {
        "cancel_url": "http://paypal.com/cancel",
        "return_url": "http://paypal.com/return"
    }
})
```

**Comment by Bobspadger** [comment]
Running through the demo example in Readme I get:

```
Connected to pydev debugger (build 173.3727.137)
Traceback (most recent call last):
  File "/Users/alexhellier/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3727.137/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1683, in <module>
    main()
  File "/Users/alexhellier/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3727.137/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1677, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/alexhellier/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3727.137/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1087, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/alexhellier/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/173.3727.137/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/alexhellier/GIT/ebaypaypal/test_api.py", line 23, in <module>
    "return_url": "http://paypal.com/return"
TypeError: 'dict' object is not callable
```

**Comment by bluk** [comment]
For the `start_date` and other parameters in the `SearchGetRequest`, they are query parameters so there are separate methods for them to call to add them to the request URL. You can see an example at https://github.com/paypal/PayPal-Python-SDK/pull/230/files#diff-592ca741827f12fb0772c62c4dede9bdR9 .

For the payment example, we are finalizing updates for payments and other APIs in https://github.com/paypal/PayPal-Python-SDK/pull/233 .

If you have any feedback, please leave a comment or open an issue. Thanks!

**Comment by Bobspadger** [comment]
Gotcha, I saw those but wasnt sure if they were called later in the execute etc.

Cheers, I'll go test again
